FROM python:3.11.0-alpine

WORKDIR /sanic

COPY . .

RUN pip install --upgrade pip && pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt

EXPOSE 8000

CMD ["python", "main.py"]
